### ISSUE TITLE
Add support for other mjml options

### ISSUE THREAD

**Issue by vtherry** [jpknoll/mjml-aspnetcore#17]
Hi,

I am testing your library and it works well, thanks !
I wanted to experiment inclusion of sub-templates and store them in a separated folder but there seems to be missing options to specify argument 'filePath' of the mjml2html function.
It would be great if you could implement other mjml2html options so that we could leverage sub-templates.
Thanks you for your support :)

**Comment by SebastianStehle** [comment]
Is this is still relevant? If yes, a PR would be great.
