### ISSUE TITLE
Switch to using Jering.Javascript.NodeJS

### ISSUE THREAD

**Issue by Jaben** [jpknoll/mjml-aspnetcore#7]
Microsoft.AspNetCore.NodeServices is obsolete -- switch to using this instead: https://github.com/JeringTech/Javascript.NodeJS

**Comment by joplaal** [comment]
Is there any plan to publish a Nuget version including this changes?

**Comment by SebastianStehle** [comment]
I actually don't know how. The build does not contain a `nuget publish` statement. If you provide a PR for a github action we could create a new package name.

@jpknoll Can you transfer me the ownership of the package?

**Comment by joplaal** [comment]
@SebastianStehle Sorry, I have no experience with github actions 

Probably transfering the ownership would be the best option if @jpknoll agree. Thanks for your efforts!

**Comment by chrisjacques** [comment]
Hi @SebastianStehle and @jpknoll - the latest Nuget package still has a dependency on Microsoft.AspNetCore.NodeServices. Would it be possible to publish an updated package that uses Jering.Javascript.NodeJS instead?

**Comment by SebastianStehle** [comment]
I still do not have access to nuget.

**Comment by Jaben** [comment]
@jpknoll  Any update on providing access to the nuget? Thanks

**Comment by jpknoll** [comment]
Hi all! Sorry about not responding. I can given someone ownership permission on the nuget package, I just need nuget.org username to hand off to.

**Comment by jpknoll** [comment]
I've send a request to @Jaben, as it appears to be the same person :-)

**Comment by SebastianStehle** [comment]
Can you also invite me: https://www.nuget.org/profiles/sebastianstehle ?

**Comment by jpknoll** [comment]
Sent!

**Comment by SebastianStehle** [comment]
Awesome. If it is okay for you, you could also make as maintainer of the repo. Then we can upload the nuget secret and deploy it with a github action

**Comment by jpknoll** [comment]
Hmm, that doesn't appear to be an option, probably because the project is attached to me.
https://stackoverflow.com/questions/8015579/add-another-user-to-project-owners-in-github#8015918

**Comment by jpknoll** [comment]
(Happy to transfer ownership to an organization that can properly own maintenance)

**Comment by SebastianStehle** [comment]
okay

**Comment by SebastianStehle** [comment]
Create the org: https://github.com/mjml-aspnetcore

**Comment by jpknoll** [comment]
Done!

**Comment by SebastianStehle** [comment]
I have completed it:

* Migrated to Repository
* Created a github action
* Published a new version

**Comment by Jaben** [comment]
Thanks! @SebastianStehle
